[E 231207 12:21:58 historical_data:14] Invalid Token: The provided token is not valid.
[I 231207 13:13:06 historical_data:60] Logout Successfull
[I 231207 13:28:43 historical_data:60] Logout Successfull
[E 231207 22:38:19 historical_data:71] Historic Api failed: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 196, in _request
        data = json.loads(r.content.decode("utf8"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/angelOne/historical_data.py", line 69, in <module>
        print( smartApi.getCandleData(historicParam))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 430, in getCandleData
        getCandleDataResponse=self._postRequest("api.candle.data",historicDataParams)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 228, in _postRequest
        return self._request(route, "POST", params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 199, in _request
        raise ex.DataException("Couldn't parse the JSON response received from the server: {content}".format(
    SmartApi.smartExceptions.DataException: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
[E 231207 22:38:20 historical_data:71] Historic Api failed: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 196, in _request
        data = json.loads(r.content.decode("utf8"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/angelOne/historical_data.py", line 69, in <module>
        print( smartApi.getCandleData(historicParam))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 430, in getCandleData
        getCandleDataResponse=self._postRequest("api.candle.data",historicDataParams)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 228, in _postRequest
        return self._request(route, "POST", params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 199, in _request
        raise ex.DataException("Couldn't parse the JSON response received from the server: {content}".format(
    SmartApi.smartExceptions.DataException: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
[E 231207 22:38:20 historical_data:71] Historic Api failed: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 196, in _request
        data = json.loads(r.content.decode("utf8"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/angelOne/historical_data.py", line 69, in <module>
        print( smartApi.getCandleData(historicParam))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 430, in getCandleData
        getCandleDataResponse=self._postRequest("api.candle.data",historicDataParams)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 228, in _postRequest
        return self._request(route, "POST", params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 199, in _request
        raise ex.DataException("Couldn't parse the JSON response received from the server: {content}".format(
    SmartApi.smartExceptions.DataException: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
[E 231207 22:38:21 historical_data:71] Historic Api failed: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 196, in _request
        data = json.loads(r.content.decode("utf8"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/angelOne/historical_data.py", line 69, in <module>
        print( smartApi.getCandleData(historicParam))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 430, in getCandleData
        getCandleDataResponse=self._postRequest("api.candle.data",historicDataParams)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 228, in _postRequest
        return self._request(route, "POST", params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 199, in _request
        raise ex.DataException("Couldn't parse the JSON response received from the server: {content}".format(
    SmartApi.smartExceptions.DataException: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
[E 231207 22:38:21 historical_data:71] Historic Api failed: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 196, in _request
        data = json.loads(r.content.decode("utf8"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/angelOne/historical_data.py", line 69, in <module>
        print( smartApi.getCandleData(historicParam))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 430, in getCandleData
        getCandleDataResponse=self._postRequest("api.candle.data",historicDataParams)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 228, in _postRequest
        return self._request(route, "POST", params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 199, in _request
        raise ex.DataException("Couldn't parse the JSON response received from the server: {content}".format(
    SmartApi.smartExceptions.DataException: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
[E 231207 22:38:23 historical_data:71] Historic Api failed: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 196, in _request
        data = json.loads(r.content.decode("utf8"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/angelOne/historical_data.py", line 69, in <module>
        print( smartApi.getCandleData(historicParam))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 430, in getCandleData
        getCandleDataResponse=self._postRequest("api.candle.data",historicDataParams)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 228, in _postRequest
        return self._request(route, "POST", params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 199, in _request
        raise ex.DataException("Couldn't parse the JSON response received from the server: {content}".format(
    SmartApi.smartExceptions.DataException: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
[E 231207 22:38:23 historical_data:71] Historic Api failed: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 196, in _request
        data = json.loads(r.content.decode("utf8"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/angelOne/historical_data.py", line 69, in <module>
        print( smartApi.getCandleData(historicParam))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 430, in getCandleData
        getCandleDataResponse=self._postRequest("api.candle.data",historicDataParams)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 228, in _postRequest
        return self._request(route, "POST", params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 199, in _request
        raise ex.DataException("Couldn't parse the JSON response received from the server: {content}".format(
    SmartApi.smartExceptions.DataException: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
[E 231207 22:38:23 historical_data:71] Historic Api failed: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 196, in _request
        data = json.loads(r.content.decode("utf8"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/angelOne/historical_data.py", line 69, in <module>
        print( smartApi.getCandleData(historicParam))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 430, in getCandleData
        getCandleDataResponse=self._postRequest("api.candle.data",historicDataParams)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 228, in _postRequest
        return self._request(route, "POST", params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 199, in _request
        raise ex.DataException("Couldn't parse the JSON response received from the server: {content}".format(
    SmartApi.smartExceptions.DataException: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
[E 231207 22:38:23 historical_data:71] Historic Api failed: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 196, in _request
        data = json.loads(r.content.decode("utf8"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/angelOne/historical_data.py", line 69, in <module>
        print( smartApi.getCandleData(historicParam))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 430, in getCandleData
        getCandleDataResponse=self._postRequest("api.candle.data",historicDataParams)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 228, in _postRequest
        return self._request(route, "POST", params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 199, in _request
        raise ex.DataException("Couldn't parse the JSON response received from the server: {content}".format(
    SmartApi.smartExceptions.DataException: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
[E 231207 22:38:24 historical_data:71] Historic Api failed: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 196, in _request
        data = json.loads(r.content.decode("utf8"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/angelOne/historical_data.py", line 69, in <module>
        print( smartApi.getCandleData(historicParam))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 430, in getCandleData
        getCandleDataResponse=self._postRequest("api.candle.data",historicDataParams)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 228, in _postRequest
        return self._request(route, "POST", params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 199, in _request
        raise ex.DataException("Couldn't parse the JSON response received from the server: {content}".format(
    SmartApi.smartExceptions.DataException: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
[E 231207 22:38:24 historical_data:71] Historic Api failed: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 196, in _request
        data = json.loads(r.content.decode("utf8"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/angelOne/historical_data.py", line 69, in <module>
        print( smartApi.getCandleData(historicParam))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 430, in getCandleData
        getCandleDataResponse=self._postRequest("api.candle.data",historicDataParams)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 228, in _postRequest
        return self._request(route, "POST", params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 199, in _request
        raise ex.DataException("Couldn't parse the JSON response received from the server: {content}".format(
    SmartApi.smartExceptions.DataException: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
[E 231207 22:38:25 historical_data:71] Historic Api failed: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 196, in _request
        data = json.loads(r.content.decode("utf8"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/angelOne/historical_data.py", line 69, in <module>
        print( smartApi.getCandleData(historicParam))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 430, in getCandleData
        getCandleDataResponse=self._postRequest("api.candle.data",historicDataParams)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 228, in _postRequest
        return self._request(route, "POST", params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 199, in _request
        raise ex.DataException("Couldn't parse the JSON response received from the server: {content}".format(
    SmartApi.smartExceptions.DataException: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
[E 231207 22:38:25 historical_data:71] Historic Api failed: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 196, in _request
        data = json.loads(r.content.decode("utf8"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/angelOne/historical_data.py", line 69, in <module>
        print( smartApi.getCandleData(historicParam))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 430, in getCandleData
        getCandleDataResponse=self._postRequest("api.candle.data",historicDataParams)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 228, in _postRequest
        return self._request(route, "POST", params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 199, in _request
        raise ex.DataException("Couldn't parse the JSON response received from the server: {content}".format(
    SmartApi.smartExceptions.DataException: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
[E 231207 22:38:26 historical_data:71] Historic Api failed: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 196, in _request
        data = json.loads(r.content.decode("utf8"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/angelOne/historical_data.py", line 69, in <module>
        print( smartApi.getCandleData(historicParam))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 430, in getCandleData
        getCandleDataResponse=self._postRequest("api.candle.data",historicDataParams)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 228, in _postRequest
        return self._request(route, "POST", params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 199, in _request
        raise ex.DataException("Couldn't parse the JSON response received from the server: {content}".format(
    SmartApi.smartExceptions.DataException: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
[E 231207 22:38:27 historical_data:71] Historic Api failed: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 196, in _request
        data = json.loads(r.content.decode("utf8"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/angelOne/historical_data.py", line 69, in <module>
        print( smartApi.getCandleData(historicParam))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 430, in getCandleData
        getCandleDataResponse=self._postRequest("api.candle.data",historicDataParams)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 228, in _postRequest
        return self._request(route, "POST", params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 199, in _request
        raise ex.DataException("Couldn't parse the JSON response received from the server: {content}".format(
    SmartApi.smartExceptions.DataException: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
[E 231207 22:38:28 historical_data:71] Historic Api failed: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 196, in _request
        data = json.loads(r.content.decode("utf8"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/angelOne/historical_data.py", line 69, in <module>
        print( smartApi.getCandleData(historicParam))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 430, in getCandleData
        getCandleDataResponse=self._postRequest("api.candle.data",historicDataParams)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 228, in _postRequest
        return self._request(route, "POST", params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 199, in _request
        raise ex.DataException("Couldn't parse the JSON response received from the server: {content}".format(
    SmartApi.smartExceptions.DataException: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
[E 231207 22:38:29 historical_data:71] Historic Api failed: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 196, in _request
        data = json.loads(r.content.decode("utf8"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/angelOne/historical_data.py", line 69, in <module>
        print( smartApi.getCandleData(historicParam))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 430, in getCandleData
        getCandleDataResponse=self._postRequest("api.candle.data",historicDataParams)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 228, in _postRequest
        return self._request(route, "POST", params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 199, in _request
        raise ex.DataException("Couldn't parse the JSON response received from the server: {content}".format(
    SmartApi.smartExceptions.DataException: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
[E 231207 22:38:29 historical_data:71] Historic Api failed: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 196, in _request
        data = json.loads(r.content.decode("utf8"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/angelOne/historical_data.py", line 69, in <module>
        print( smartApi.getCandleData(historicParam))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 430, in getCandleData
        getCandleDataResponse=self._postRequest("api.candle.data",historicDataParams)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 228, in _postRequest
        return self._request(route, "POST", params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 199, in _request
        raise ex.DataException("Couldn't parse the JSON response received from the server: {content}".format(
    SmartApi.smartExceptions.DataException: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
[E 231207 22:38:30 historical_data:71] Historic Api failed: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 196, in _request
        data = json.loads(r.content.decode("utf8"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/angelOne/historical_data.py", line 69, in <module>
        print( smartApi.getCandleData(historicParam))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 430, in getCandleData
        getCandleDataResponse=self._postRequest("api.candle.data",historicDataParams)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 228, in _postRequest
        return self._request(route, "POST", params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 199, in _request
        raise ex.DataException("Couldn't parse the JSON response received from the server: {content}".format(
    SmartApi.smartExceptions.DataException: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
[E 231207 22:38:30 historical_data:71] Historic Api failed: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 196, in _request
        data = json.loads(r.content.decode("utf8"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/angelOne/historical_data.py", line 69, in <module>
        print( smartApi.getCandleData(historicParam))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 430, in getCandleData
        getCandleDataResponse=self._postRequest("api.candle.data",historicDataParams)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 228, in _postRequest
        return self._request(route, "POST", params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 199, in _request
        raise ex.DataException("Couldn't parse the JSON response received from the server: {content}".format(
    SmartApi.smartExceptions.DataException: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
[E 231207 22:38:30 historical_data:71] Historic Api failed: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 196, in _request
        data = json.loads(r.content.decode("utf8"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/angelOne/historical_data.py", line 69, in <module>
        print( smartApi.getCandleData(historicParam))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 430, in getCandleData
        getCandleDataResponse=self._postRequest("api.candle.data",historicDataParams)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 228, in _postRequest
        return self._request(route, "POST", params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 199, in _request
        raise ex.DataException("Couldn't parse the JSON response received from the server: {content}".format(
    SmartApi.smartExceptions.DataException: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
[E 231207 22:38:31 historical_data:71] Historic Api failed: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 196, in _request
        data = json.loads(r.content.decode("utf8"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/angelOne/historical_data.py", line 69, in <module>
        print( smartApi.getCandleData(historicParam))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 430, in getCandleData
        getCandleDataResponse=self._postRequest("api.candle.data",historicDataParams)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 228, in _postRequest
        return self._request(route, "POST", params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 199, in _request
        raise ex.DataException("Couldn't parse the JSON response received from the server: {content}".format(
    SmartApi.smartExceptions.DataException: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
[E 231207 22:38:31 historical_data:71] Historic Api failed: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 196, in _request
        data = json.loads(r.content.decode("utf8"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/ayush/Desktop/angelone_smartapi/angelOne/historical_data.py", line 69, in <module>
        print( smartApi.getCandleData(historicParam))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 430, in getCandleData
        getCandleDataResponse=self._postRequest("api.candle.data",historicDataParams)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 228, in _postRequest
        return self._request(route, "POST", params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ayush/Desktop/angelone_smartapi/venv/lib/python3.11/site-packages/SmartApi/smartConnect.py", line 199, in _request
        raise ex.DataException("Couldn't parse the JSON response received from the server: {content}".format(
    SmartApi.smartExceptions.DataException: Couldn't parse the JSON response received from the server: b'Access denied because of exceeding access rate'
